# Generated by Django 4.0.1 on 2022-02-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='antecedentes_ginecoobstericos',
            new_name='antecedentes_ginecoobstétricos',
        ),
    ]
