# Generated by Django 4.0.1 on 2022-02-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_antecedentes_ginecoobstericos_historiaclinica_antecedentes_ginecoobstétricos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='motivo_actualizacion',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
    ]
