# Generated by Django 4.0.3 on 2022-03-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_historiaclinica_motivo_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipoAfilliacion', models.CharField(choices=[('CC', 'Cedula'), ('TI', 'Tarjetaidentidad'), ('PA', 'Pasaporte')], default='CC', max_length=2)),
                ('noAfiliacion', models.BigIntegerField()),
                ('aseguradora', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(choices=[('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Mestizo', 'Mestizo')], default='Blanco', max_length=20)),
                ('etnicidad', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.informacionpaciente'),
            preserve_default=False,
        ),
    ]
