# Generated by Django 4.0.3 on 2022-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_informacionpaciente_historiaclinica_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpaciente',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
